In [1]:
import utils
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.utils import resample
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
import warnings
warnings.filterwarnings('ignore')

In [3]:
dictSize = 225
(X, y) = utils.loadData( "train", dictSize = dictSize )

In [4]:
np.unique(y,return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 34., 35., 37., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48., 49., 50.]),
 array([1424, 2558, 1509, 1475,   89,    9,  278,  290,  293,  291,  155,
         154,  151,    9,  105,  116,   43,   21,   63,   62,   41,   40,
          73,   50,   66,   58,    3,   46,   40,   52,   12,   49,   31,
          48,   27,   25,    9,   23,   32,   28,   28,   19,   16,   23,
          29,   14,   23], dtype=int64))

In [5]:
y_t = y.reshape(y.shape[0],1)
y_t

array([[ 1.],
       [ 2.],
       [ 4.],
       ...,
       [ 2.],
       [32.],
       [ 3.]])

In [8]:
x_t = X.toarray()
x_t

array([[0., 0., 2., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
x_t = np.hstack((x_t,y_t))
x_t

array([[ 0.,  0.,  2., ...,  0.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  2.],
       [ 0.,  0.,  0., ...,  0.,  4.,  4.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  2.,  2.],
       [ 0.,  0.,  0., ...,  0., 32., 32.],
       [ 0.,  0.,  0., ...,  0.,  3.,  3.]])

In [11]:
data = pd.DataFrame(x_t)

In [76]:
temp1 = data[data.iloc[:,225]==6]

In [77]:
temp2 = data[data.iloc[:,225]==14]

In [78]:
temp3 = data[data.iloc[:,225]==18]

In [79]:
temp4 = data[data.iloc[:,225]==27]

In [80]:
temp5  = data[data.iloc[:,225]==40]

In [81]:
temp6  = data[data.iloc[:,225]==45]
temp7  = data[data.iloc[:,225]==46]
temp8  = data[data.iloc[:,225]==47]
temp9  = data[data.iloc[:,225]==48]
temp10  = data[data.iloc[:,225]==49]
temp11  = data[data.iloc[:,225]==50]

In [82]:
_temp1 = resample(temp1, replace=True,n_samples=1000,random_state=123)
_temp2 = resample(temp2, replace=True,n_samples=1000,random_state=123)
_temp3 = resample(temp3, replace=True,n_samples=300,random_state=123)
_temp4 = resample(temp4, replace=True,n_samples=300,random_state=123)
_temp5 = resample(temp5, replace=True,n_samples=300,random_state=123)
_temp6 = resample(temp6, replace=True,n_samples=300,random_state=123)
_temp7 = resample(temp7, replace=True,n_samples=300,random_state=123)
_temp8 = resample(temp8, replace=True,n_samples=300,random_state=123)
_temp9 = resample(temp9, replace=True,n_samples=300,random_state=123)
_temp10 = resample(temp10, replace=True,n_samples=300,random_state=123)
_temp11 = resample(temp11, replace=True,n_samples=300,random_state=123)

In [83]:
t_data = pd.concat([data,_temp1,_temp2,temp3,temp4,temp5,temp6,temp7,temp8,temp9,temp10,temp11])

In [84]:
t_data.shape

(12157, 226)

In [85]:
n_data = t_data.to_numpy()

In [86]:
X = n_data[:,:-1]

In [87]:
y = n_data[:,-1]

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify=y)

In [89]:
o_vs_r = OneVsRestClassifier(LogisticRegression())
ovsr = o_vs_r.fit(X_train, y_train)

C:\Users\Asus\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Asus\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [98]:
y_pred = o_vs_r.predict_proba(X_test)

In [94]:
# np.average(y_test == y_pred)

0.8130608175473579

In [95]:
# precision_score(y_test, y_pred,average='weighted')


C:\Users\Asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.7962875819528371

In [96]:
# recall_score(y_test, y_pred,average='weighted')

0.8130608175473579

In [99]:
y_pred = np.insert(y_pred,32,0,axis=1)
y_pred = np.insert(y_pred,35,0,axis=1)
y_pred = np.insert(y_pred,37,0,axis=1)
y_t = np.argsort(-y_pred)[:,:5]

In [100]:
y_t = np.argsort(-y_pred)[:,:5]+1

In [101]:
preck = utils.getPrecAtK( y_test, y_t, 5 )

In [102]:
print( "prec@1: %0.3f" % preck[0], "prec@3: %0.3f" % preck[2], "prec@5: %0.3f" % preck[4] )

prec@1: 0.813 prec@3: 0.925 prec@5: 0.964


In [103]:
mpreck = utils.getMPrecAtK( y_test, y_t, 5 )

In [104]:
print( "mprec@1: %0.3e" % mpreck[0], "mprec@3: %0.3e" % mpreck[2], "mprec@5: %0.3e" % mpreck[4] )

mprec@1: 5.299e-01 mprec@3: 7.557e-01 mprec@5: 8.805e-01
